# Generated by Django 5.0.3 on 2024-03-20 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=225, null=True)),
                ('nrc_no', models.CharField(max_length=225, unique=True)),
                ('fathername', models.CharField(max_length=225)),
                ('mothername', models.CharField(max_length=225)),
                ('phone', models.CharField(blank=True, max_length=225, null=True)),
                ('address', models.TextField()),
                ('gender', models.CharField(blank=True, max_length=225, null=True)),
                ('dob', models.DateField()),
                ('marital', models.CharField(blank=True, max_length=225, null=True)),
                ('entrydate', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('familytable', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('att_hr', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee_profile')),
            ],
        ),
    ]
