# Generated by Django 5.0.3 on 2024-03-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_gender_alter_employee_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='daily_rate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee_profile',
            name='salary',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
