# Generated by Django 5.0.3 on 2024-03-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_profile_daily_rate_employee_profile_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
