# Generated by Django 5.0.3 on 2024-03-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=225)),
                ('iunit', models.CharField(blank=True, max_length=255, null=True)),
                ('saleprice', models.PositiveIntegerField(default=0)),
                ('purchaseprice', models.PositiveIntegerField(default=0)),
                ('stockbalance', models.IntegerField(default=0)),
                ('superitem', models.CharField(blank=True, max_length=255, null=True)),
                ('unpackqty', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.TextField(max_length=255)),
            ],
        ),
    ]
